title: Chang M. Yun
logo: /assets/img/photo.png
description: "<b>PhD Candidate, Stanford University</b><br>MPhil, University of Cambridge<br>BSc, Columbia University<br><br><i>Website still in progress..!</i><br><br>Contact: chang.m.yun [at] stanford [dot] edu"
theme: jekyll-theme-minimal
